### PR TITLE
ThreadFreezer: Fix an exception that could occur with NtGetNextThread

### LINKED ISSUE #30: NtGetNextThread exception in UWP apps
For some reason in Minecraft `NtGetNextThread` throws an exception with code `0xC0000008: An invalid handle was specified.`, causing game crash, this is a UWP game afaik but I did use some launcher to set it up to let me copy DLLs into it.

IIRC some APIs are restricted in UWP land, guess maybe NtGetNextThread is one of them? Never had this exception in any non-UWP apps at least.

Call stack:
```C
 	ntdll.dll!KiRaiseUserExceptionDispatcher()	Unknown
>	dxgi.dll!safetyhook::ThreadFreezer::ThreadFreezer(void)	C++
 	dxgi.dll!safetyhook::InlineHook::e9_hook(class std::shared_ptr<class safetyhook::Allocator> const &)	C++
 	dxgi.dll!safetyhook::InlineHook::create(class std::shared_ptr<class safetyhook::Allocator> const &,unsigned __int64,unsigned __int64)	C++
 	dxgi.dll!safetyhook::InlineHook::create(unsigned __int64,unsigned __int64)	C++
 	dxgi.dll!safetyhook::create_inline(void *,void *)	C++
 	dxgi.dll!nvngx::init(struct HINSTANCE__ *)	C++
```

FWIW the older toolhelp method did used to work fine on this game too.

If you own Minecraft Bedrock (or have Xbox Game Pass PC) you can use https://github.com/bedrockLauncher/BedrockLauncher to set the game up in a writable folder, then build a wrapper DLL to load into it and try creating an inline hook.

E: strange, if I run with debugger attached and manually continue past the exception it runs fine, seems that some of the calls to NtGetNextThread are also successful too, not sure why this is causing a crash when debugger isn't attached...
(also disabling the exception type in VS debugger is still making it prompt for each exception too, not sure if that means anything)

### PR DESCRIPTION
**Pull request by cursey**
Closes #30

### CODE REVIEW

File: src/thread_freezer.cpp [hunk 1]
```diff
@@ -16,28 +16,36 @@ NtGetNextThread(HANDLE ProcessHandle, HANDLE ThreadHandle, ACCESS_MASK DesiredAc
 
 namespace safetyhook {
 ThreadFreezer::ThreadFreezer() {
+    m_frozen_threads.reserve(1024);
```
Comment (SamRoyDev) [inline src/thread_freezer.cpp:19]: Is it possible we would need more than 1024 reserved?

Comment (angelfor3v3r) [reply src/thread_freezer.cpp:19]: > Is it possible we would need more than 1024 reserved?

It's not ideal. I think @cursey has some other ideas on how to approach this but this was a quick and easy solution. The allocations done here are the issue I believe. Cursey would know more about it though since he's the one looking into it.

Comment (cursey) [reply src/thread_freezer.cpp]: The problem was under certain circumstances the default C++ allocator would call `new` which would randomly deadlock during thread freezing (only ever saw this with debug builds but it may have been an issue in release as well).

Pre-allocating was just a quick fix solution I came up with @ 5am. I've pushed a commit that removes this and just uses a custom allocator where I am no longer running into the deadlock.

File: src/thread_freezer.cpp [hunk 2]
```diff
@@ -15,71 +15,112 @@ NtGetNextThread(HANDLE ProcessHandle, HANDLE ThreadHandle, ACCESS_MASK DesiredAc
...
+                continue;
+            }
+
+            const auto suspend_count = SuspendThread(thread);
+
+            if (suspend_count == static_cast<DWORD>(-1)) {
+                continue;
+            }
+
+            if (suspend_count != 0) { // Thread was already suspended.
```
Comment (emoose) [inline src/thread_freezer.cpp:54]: If this is using ResumeThread on already suspended threads here, might that mean the later thread resuming block would end up resuming the thread, even though it was already suspended outside of ThreadFreezer?

Might it be better to remove this block so that the suspend count would be incremented, so that the later resume block only decrements instead of actually resuming?

Comment (cursey) [reply src/thread_freezer.cpp]: I've modified the logic here to account for threads that were already frozen (f579cbf74e2d664bcaa354c07c2d2f290a148915). Give it a try and let me know how it works.

Comment (emoose) [reply src/thread_freezer.cpp]: Mostly seems good, tried with a few different games (CP2077/Witcher3/RDR2/TLOU) and by itself worked fine.

Also tested with the scenario I mentioned with all the mod tools, for CP2077/Witcher3/RDR2 it always seemed to work fine (which is a good sign since CP2077 did give ThreadFreezer issues before)

With TLOU it seems using SpecialK with safetyhook DLL has a rare chance of freezing on launch though, happened maybe 1 in 10 times I tried to launch, after removing either one of them I couldn't get freezing to happen again.
Odd thing is my safetyhook DLL was dynamically loaded as nvngx.dll, long after SpecialKs DllMain or games WinMain would have ran...
Maybe SK is doing something that delays hooking until later on, close to when nvngx.dll is loaded in maybe, not really sure how to look into that more though.

TLOU is a pretty notorious bad port though and apparently does weird things with CPU cores, maybe that's part of why this only seemed to happen with that.
(that did make me wonder if doing something with `SetProcessAffinityMask` before freezing could be worth looking into though?)
